### ISSUE TITLE
occ suspiciouslogin:optimize --stats causes an exception to be thrown

### ISSUE THREAD

**Issue by j-ed** [nextcloud/suspicious_login#188]
Nextcloud version: 17.0.1
Suspicious login app version: 2.4.1

The app itself seems to works as expected, but the execution of the following command causes an exception to be thrown:
```
./occ suspiciouslogin:optimize --stats
An unhandled exception has been thrown:
TypeError: Argument 2 passed to OCA\SuspiciousLogin\Service\MLP\Optimizer::optimize() must be an instance of OCA\SuspiciousLogin\Service\IClassificationStrategy, null given, called in NEXTCLOUD_DOC_ROOT/apps2/suspicious_login/lib/Command/Optimize.php on line 56 and defined in NEXTCLOUD_DOC_ROOT/apps2/suspicious_login/lib/Service/MLP/Optimizer.php:151
Stack trace:
#0 NEXTCLOUD_DOC_ROOT/apps2/suspicious_login/lib/Command/Optimize.php(56): OCA\SuspiciousLogin\Service\MLP\Optimizer->optimize(100, NULL, Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 NEXTCLOUD_DOC_ROOT/3rdparty/symfony/console/Command/Command.php(255): OCA\SuspiciousLogin\Command\Optimize->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 NEXTCLOUD_DOC_ROOT/3rdparty/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 NEXTCLOUD_DOC_ROOT/3rdparty/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(OCA\SuspiciousLogin\Command\Optimize), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 NEXTCLOUD_DOC_ROOT/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 NEXTCLOUD_DOC_ROOT/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 NEXTCLOUD_DOC_ROOT/console.php(97): OC\Console\Application->run()
#7 NEXTCLOUD_DOC_ROOT/occ(11): require_once('NEXTCLOUD_DOC_ROOT...')
```

**Comment by ChristophWurst** [comment]
Please test https://github.com/nextcloud/suspicious_login/pull/189 https://patch-diff.githubusercontent.com/raw/nextcloud/suspicious_login/pull/189.patch

**Comment by j-ed** [comment]
@ChristophWurst Incredible, you're faster than light 😉 I think it looks much better now, although I don't know how many coffees I have to drink until it finishes:
```
> ./occ suspiciouslogin:optimize --stats
Optimizing a MLP trainer in 100 steps. Enjoy your coffee!

Epoch 0: epochs= 443 layers=12 shuffledRate=1.500 randomRate=1.081, learningRate=0.057
  Step width for next config neighbor: 0.8
Epoch 1: epochs= 390 layers=13 shuffledRate=1.500 randomRate=0.639, learningRate=0.076
  Step width for next config neighbor: 0.8
  Result got worse: 0.95188714303814->0.94655344382768
Epoch 2: epochs= 279 layers= 9 shuffledRate=1.176 randomRate=0.900, learningRate=0.070
  Step width for next config neighbor: 0.788
  Result got worse: 0.95188714303814->0.94614394707304
Epoch 3: epochs= 548 layers=12 shuffledRate=0.990 randomRate=1.377, learningRate=0.076
  Step width for next config neighbor: 0.77618
  Result got worse: 0.95188714303814->0.93428117339547
Epoch 4: epochs= 291 layers=10 shuffledRate=1.500 randomRate=0.606, learningRate=0.065
  Step width for next config neighbor: 0.7645373
  Result got worse: 0.95188714303814->0.94304861644041
Epoch 5: epochs= 264 layers=14 shuffledRate=1.245 randomRate=1.212, learningRate=0.034
  Step width for next config neighbor: 0.7530692405
...
```
Just one small cosmetic thing I realized, there is a supernumerary white-space between the `epochs=` and the following figure e.g. `291`, which is different to the following values being displayed.

**Comment by ChristophWurst** [comment]
lol, yeah, that message is from a time where I had very little training data. I think you shouldn't wait for the completion. Haven't done such a optimization run in a few months (default params seem to do well on most systems) but please let me know the results!

It might take a day to finish.  It totally depends on which area of the parameter space the algorithm settles :see_no_evil:

**Comment by ChristophWurst** [comment]
Also please note that I later realized that this optimization run has a little flaw in that it doesn't ensure to always test on the exact same data. The results aren't scientifically correct.

**Comment by ChristophWurst** [comment]
> Just one small cosmetic thing I realized, there is a supernumerary white-space between the `epochs=` and the following figure e.g. `291`, which is different to the following values being displayed.

If you shoot a PR I'll integrate it!
