### ISSUE TITLE
Error when trying to compile the app

### ISSUE THREAD

**Issue by szaimen** [nextcloud/suspicious_login#536]
I've got the following error when trying to compile the app from master via `npm ci` and `npm run build`:

```
> webpack --progress --config src/webpack.prod.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
[webpack-cli] Error: Cannot find module '@nextcloud/browserslist-config'
Require stack:
- /var/www/html/apps/suspicious_login/node_modules/browserslist/node.js
- /var/www/html/apps/suspicious_login/node_modules/browserslist/index.js
- /var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/browserslistTargetHandler.js
- /var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/target.js
- /var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/defaults.js
- /var/www/html/apps/suspicious_login/node_modules/webpack/lib/webpack.js
- /var/www/html/apps/suspicious_login/node_modules/webpack/lib/index.js
- /var/www/html/apps/suspicious_login/node_modules/webpack-cli/lib/webpack-cli.js
- /var/www/html/apps/suspicious_login/node_modules/webpack-cli/lib/bootstrap.js
- /var/www/html/apps/suspicious_login/node_modules/webpack-cli/bin/cli.js
- /var/www/html/apps/suspicious_login/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (/var/www/html/apps/suspicious_login/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
    at Object.loadQueries (/var/www/html/apps/suspicious_login/node_modules/browserslist/node.js:161:35)
    at Function.select (/var/www/html/apps/suspicious_login/node_modules/browserslist/index.js:1118:26)
    at /var/www/html/apps/suspicious_login/node_modules/browserslist/index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (/var/www/html/apps/suspicious_login/node_modules/browserslist/index.js:318:18)
    at browserslist (/var/www/html/apps/suspicious_login/node_modules/browserslist/index.js:444:21)
    at Object.load (/var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/browserslistTargetHandler.js:70:9)
    at getDefaultTarget (/var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/target.js:19:50)
    at /var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/defaults.js:130:10
    at F (/var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/defaults.js:71:15)
    at applyWebpackOptionsDefaults (/var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/defaults.js:129:2)
    at createCompiler (/var/www/html/apps/suspicious_login/node_modules/webpack/lib/webpack.js:78:2)
    at create (/var/www/html/apps/suspicious_login/node_modules/webpack/lib/webpack.js:127:16)
    at webpack (/var/www/html/apps/suspicious_login/node_modules/webpack/lib/webpack.js:135:47) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/html/apps/suspicious_login/node_modules/browserslist/node.js',
    '/var/www/html/apps/suspicious_login/node_modules/browserslist/index.js',
    '/var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/browserslistTargetHandler.js',
    '/var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/target.js',
    '/var/www/html/apps/suspicious_login/node_modules/webpack/lib/config/defaults.js',
    '/var/www/html/apps/suspicious_login/node_modules/webpack/lib/webpack.js',
    '/var/www/html/apps/suspicious_login/node_modules/webpack/lib/index.js',
    '/var/www/html/apps/suspicious_login/node_modules/webpack-cli/lib/webpack-cli.js',
    '/var/www/html/apps/suspicious_login/node_modules/webpack-cli/lib/bootstrap.js',
    '/var/www/html/apps/suspicious_login/node_modules/webpack-cli/bin/cli.js',
    '/var/www/html/apps/suspicious_login/node_modules/webpack/bin/webpack.js'
  ]
}
```
I've used  node v14.17.6 (npm v7.24.0)

**Comment by szaimen** [comment]
You should be able to reproduce this easily by running:

```
docker run -it \
-e SERVER_BRANCH=master \
-e SUSPICIOUSLOGIN_BRANCH=master \
--name nextcloud-easy-test \
-p 127.0.0.1:8443:443 \
ghcr.io/szaimen/nextcloud-easy-test:latest

```

**Comment by nickvergessen** [comment]
Sounds like https://github.com/nextcloud/suspicious_login/issues/179 was partly done? xD

**Comment by nickvergessen** [comment]
Works fine here 
```
npm run build

> suspicious_login@4.0.0 build
> webpack --progress --config src/webpack.prod.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
asset settings.js 511 KiB [compared for emit] [minimized] [big] (name: settings) 2 related assets
orphan modules 244 KiB [orphan] 19 modules
runtime modules 1010 bytes 5 modules
modules by path ./node_modules/moment/ 574 KiB
  modules by path ./node_modules/moment/locale/*.js 424 KiB 127 modules
  ./node_modules/moment/moment.js 147 KiB [built] [code generated]
  ./node_modules/moment/locale/ sync ^\.\/.*$ 3 KiB [optional] [built] [code generated]
modules by path ./node_modules/core-js/ 26.2 KiB 54 modules
./src/main-settings.js + 19 modules 245 KiB [built] [code generated]
./node_modules/@nextcloud/initial-state/dist/index.js 829 bytes [built] [code generated]
./node_modules/chart.js/dist/Chart.js 433 KiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  settings.js (511 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  settings (511 KiB)
      settings.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.39.1 compiled with 3 warnings in 7287 ms
```

node v14.17.0 npm v7.20.6

**Comment by szaimen** [comment]
Then it is probably the node and npm version. Strange since any app that I tried until now (that requires node 14 or higher) works with the mentioned node and npm combination.

**Comment by nickvergessen** [comment]
Or you just make a PR to finish #179 that should also solve your issue?

**Comment by szaimen** [comment]
Hm... Not sure how to do that. :/

**Comment by nickvergessen** [comment]
Add `@nextcloud/browserslist-config` as a dev dependency with npm and extend the package.json like shown in the readme of the `@nextcloud/browserslist-config` repo

**Comment by szaimen** [comment]
Sry but that is currently out of scope for me. But thanks for the instructions!
