### ISSUE TITLE
Dependency hell with server's doctrine/lexer

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/suspicious_login#896]
This app loads doctrine/lexer through the CS fixer. On a dev install, this can cause the server email validation to fail:

```
TypeError: Cannot assign array to property Egulias\EmailValidator\EmailLexer::$current of type Doctrine\Common\Lexer\Token in /var/www/nextcloud/3rdparty/egulias/email-validator/src/EmailLexer.php:211
Stack trace:
#0 /var/www/nextcloud/3rdparty/egulias/email-validator/src/Parser.php(74): Egulias\EmailValidator\EmailLexer->moveNext()
#1 /var/www/nextcloud/3rdparty/egulias/email-validator/src/EmailParser.php(38): Egulias\EmailValidator\Parser->hasAtToken()
#2 /var/www/nextcloud/3rdparty/egulias/email-validator/src/Parser.php(43): Egulias\EmailValidator\EmailParser->preLeftParsing()
#3 /var/www/nextcloud/3rdparty/egulias/email-validator/src/EmailParser.php(29): Egulias\EmailValidator\Parser->parse('ncdev@domain...')
#4 /var/www/nextcloud/3rdparty/egulias/email-validator/src/Validation/RFCValidation.php(27): Egulias\EmailValidator\EmailParser->parse('ncdev@domain...')
#5 /var/www/nextcloud/3rdparty/egulias/email-validator/src/Validation/NoRFCWarningsValidation.php(21): Egulias\EmailValidator\Validation\RFCValidation->isValid('ncdev@domain...', Object(Egulias\EmailValidator\EmailLexer))
#6 /var/www/nextcloud/3rdparty/egulias/email-validator/src/EmailValidator.php(37): Egulias\EmailValidator\Validation\NoRFCWarningsValidation->isValid('ncdev@domain...', Object(Egulias\EmailValidator\EmailLexer))
#7 /var/www/nextcloud/lib/private/Mail/Mailer.php(248): Egulias\EmailValidator\EmailValidator->isValid('ncdev@domain...', Object(Egulias\EmailValidator\Validation\NoRFCWarningsValidation))
#8 /var/www/nextcloud/lib/public/Util.php(308): OC\Mail\Mailer->validateMailAddress('ncdev@domain...')
#9 /var/www/nextcloud/apps/settings/lib/AppInfo/Application.php(155): OCP\Util::getDefaultEmailAddress('ncdev')
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(153): OCA\Settings\AppInfo\Application->OCA\Settings\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#11 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#12 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet('OCA\\Settings\\Ma...')
#13 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(442): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Settings\\Ma...')
#14 /var/www/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Settings\\Ma...')
#15 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query('OCA\\Settings\\Ma...', true)
#16 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#17 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map(Object(Closure), Array)
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#19 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Core\\Command...')
#20 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\Core\\Command...', true)
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query('OC\\Core\\Command...')
#22 /var/www/nextcloud/lib/public/Server.php(39): OC\AppFramework\Utility\SimpleContainer->get('OC\\Core\\Command...')
#23 /var/www/nextcloud/core/register_command.php(107): OCP\Server::get('OC\\Core\\Command...')
#24 /var/www/nextcloud/lib/private/Console/Application.php(77): require_once('/var/www...')
#25 /var/www/nextcloud/console.php(81): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/nextcloud/occ(11): require_once('/var/www...')
```

Ref https://github.com/nextcloud/notifications/issues/1991

**Comment by ariep** [comment]
Hi, sorry to hijack this closed issue, but I get this exact unhandled exception -- from a simple `php occ status` -- whenever a certain somewhat experimental app (`scimserviceprovider`) is installed in Nextcloud 30. The same app code has no problem with Nextcloud 29. I'd like to try fixing that app myself but I'm rather lost with this exception which is buried in the dependency stack.

Could you maybe say a few words about the underlying cause of this exception? In your case it could apparently be solved by changing something about php-cs-fixer but I presume that has no bearing on my problem, which occurs in a production (docker) setup. Thanks for any guidance!

**Comment by ariep** [comment]
Simply bumping the dependency on `doctrine/lexer` fixes that, sorry for the noise!

**Comment by ChristophWurst** [comment]
> Could you maybe say a few words about the underlying cause of this exception?

It's documented in https://docs.nextcloud.com/server/latest/developer_manual/app_development/dependency_management.html#dependency-hell. I hope this helps.

**Comment by hanisntsolo** [comment]
> Simply bumping the dependency on `doctrine/lexer` fixes that, sorry for the noise!

What was this exactly can you come again?
