### ISSUE TITLE
 php occ suspiciouslogin:optimize fails

### ISSUE THREAD

**Issue by wriver4** [nextcloud/suspicious_login#939]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
www-data@wavecrm:~/cloud.waveguardco.net/public_html$ php occ suspiciouslogin:optimize
Optimizing a MLP trainer in 100 steps

Epoch 0: epochs= 330 layers= 2 shuffledRate=0.005 randomRate=2.000, learningRate=0.0070
  Step width for next config neighbor: 0.8
An unhandled exception has been thrown:
Amp\Parallel\Worker\TaskFailureError: Uncaught Error in worker with message "Call to undefined method Rubix\ML\Datasets\Labeled::numFeatures()" and code "0"; use Amp\Parallel\Worker\TaskFailureError::getOriginalTrace() for the stack trace in the worker in /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/parallel/lib/Worker/Internal/TaskFailure.php:60
Stack trace:
#0 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/parallel/lib/Worker/Internal/TaskFailure.php(52): Amp\Parallel\Worker\Internal\TaskFailure->createException()
#1 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/parallel/lib/Worker/TaskWorker.php(144): Amp\Parallel\Worker\Internal\TaskFailure->promise()
#2 [internal function]: Amp\Parallel\Worker\TaskWorker->Amp\Parallel\Worker\{closure}()
#3 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#4 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#5 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#6 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#7 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve()
#8 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#9 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#10 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#11 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#12 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\Loop\NativeDriver->selectStreams()
#13 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#14 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#15 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#16 /var/www/cloud.waveguardco.net/public_html/apps/mail/vendor/amphp/amp/lib/functions.php(222): Amp\Loop::run()
#17 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/lib/Service/MLP/OptimizerService.php(201): Amp\Promise\wait()
#18 /var/www/cloud.waveguardco.net/public_html/apps/suspicious_login/lib/Command/Optimize.php(80): OCA\SuspiciousLogin\Service\MLP\OptimizerService->optimize()
#19 /var/www/cloud.waveguardco.net/public_html/3rdparty/symfony/console/Command/Command.php(298): OCA\SuspiciousLogin\Command\Optimize->execute()
#20 /var/www/cloud.waveguardco.net/public_html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#21 /var/www/cloud.waveguardco.net/public_html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#22 /var/www/cloud.waveguardco.net/public_html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#23 /var/www/cloud.waveguardco.net/public_html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#24 /var/www/cloud.waveguardco.net/public_html/console.php(102): OC\Console\Application->run()
#25 /var/www/cloud.waveguardco.net/public_html/occ(11): require_once('...')
www-data@wavecrm:~/cloud.waveguardco.net/public_html$ 

### Expected behaviour
it should work.

### Actual behaviour
See Above

### Server configuration

**Web server:** Apache

**Database:** MySQL/Maria

**PHP version:**8.0.39

**Nextcloud version:** [Nextcloud Hub 8](https://cloud.waveguardco.net/) (29.0.6)
<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - announcementcenter: 7.0.0
  - appointments: 2.1.10
  - approval: 1.3.0
  - bruteforcesettings: 2.9.0
  - cadviewer: 10.10.7
  - calendar: 4.7.16
  - cfg_share_links: 6.1.0
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - collectives: 2.14.3
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - csp_editor: 1.6.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.2
  - drawio: 3.0.3
  - encryption: 2.17.0
  - event_update_notification: 2.4.0
  - external: 5.4.0
  - externalportal: 1.3.1
  - extract: 1.3.6
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_accesscontrol: 1.19.1
  - files_antivirus: 5.5.7
  - files_automatedtagging: 1.19.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_snapshots: 1.0.10
  - files_texteditor: 2.15.1
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - flow_notifications: 1.9.0
  - groupfolders: 17.0.3
  - guests: 3.1.0
  - impersonate: 1.16.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.7.8
  - metadata: 0.21.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.11.0
  - notifications: 2.17.0
  - notify_push: 0.7.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - ransomware_protection: 1.14.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - root_cache_cleaner: 0.1.8
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - sharereview: 1.2.0
  - spreed: 19.0.9
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tasks: 0.16.1
  - text: 3.10.1
  - theming: 2.4.0
  - theming_customcss: 1.17.0
  - timetracker: 0.0.83
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - user_usage_report: 1.13.1
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflow_kitinerary: 1.5.0
  - workflow_media_converter: 1.11.7
  - workflowengine: 2.11.0
Disabled:
  - audioplayer: 3.4.1 (installed 3.4.1)
  - electronicsignatures: 3.0.2 (installed 3.0.2)
  - end_to_end_encryption: 1.15.2 (installed 1.15.2)
  - files_external: 1.21.0
  - group_everyone: 0.1.16 (installed 0.1.16)
  - maps: 1.4.0 (installed 1.4.0)
  - richdocuments: 8.4.6 (installed 8.4.6)
  - richdocumentscode: 24.4.702 (installed 24.4.702)
  - support: 1.12.0 (installed 1.5.0)
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
  - video_converter: 1.0.6 (installed 1.0.6)

<details>
<summary>Nextcloud configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "167.99.1.106",
            "cloud.waveguardco.net",
            "crm.waveguardco.net",
            "wavecrm.waveguardco.net",
            "collabora.waveguardco.net",
            "waveguardco.com",
            "73.216.73.197"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/mnt\/wavecloud_data\/data\/nextcloud.log",
        "logfile_audit": "\/mnt\/wavecloud_data\/data\/audit.log",
        "dbtype": "mysql",
        "version": "29.0.6.1",
        "overwrite.cli.url": "https:\/\/cloud.waveguardco.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "lost_password_link": "disabled",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "mail_smtpsecure": "ssl",
        "theme": "",
        "loglevel": 0,
        "default_phone_region": "US",
        "app_install_overwrite": [
            "video_converter",
            "apporder",
            "ransomware_protection",
            "extract",
            "files_texteditor",
            "cfg_share_links",
            "metadata"
        ],
        "overwriteprotocol": "https",
        "mail_smtpauthtype": "LOGIN",
        "knowledgebaseenabled": false,
        "skeletondirectory": "",
        "allow_user_to_change_display_name": false,
        "login_form_autocomplete": false,
        "defaultapp": "dashboard",
        "data-fingerprint": "348693d56ab6a552d5ffcaf512b6afe8",
        "trashbin_retention_obligation": "auto, 7",
        "mail_smtpstreamoptions": {
            "ssl": {
                "security_level": 1
            }
        },
        "maintenance_window_start": 5,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "check_for_working_wellknown_setup": false
    }
}

</details>

### Browser

**Browser name:** Firefox

**Browser version:** 130.0.1

**Operating system:** Linux wavecrm 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ChristophWurst** [comment]
> #16 /var/www/cloud.waveguardco.net/public_html/apps/mail/vendor/amphp/amp/lib/functions.php(222): Amp\Loop::run()

This is a dependency hell with Mail

**Comment by ChristophWurst** [comment]
This is most likely a duplicate of https://github.com/nextcloud/suspicious_login/issues/780.

**Comment by DerDreschner** [comment]
> This is a dependency hell with Mail
Yeah, had the same issue as @wriver4. Removing Mail solved the issue.
